### ISSUE TITLE
Release 1.1.1 Missing Grid.php

### ISSUE THREAD

**Issue by scm6079** [BlackScorp/astar#5]
The current active release (1.1.1) is missing the Grid.php file and as such is inoperable (per examples and tests).   The addition of TileGraph is undocumented and missing from master, so I'm assuming this is not a planned alternative.

**Comment by BlackScorp** [comment]
Oh iam sorry, will fix it today afternoon. Actually i wanted to get rid of grid completely instead of grid i wanted to use graph or nodes or something similar since A* Pathfinding could be also used for Hexagonal grid or google map nodes or similar, but its hard to find a good class name :D

**Comment by jaseyd** [comment]
Hi. Was this issue ever resolved? I've set this library up and the tests fail immediately at the missing Grid.php file. I've tried adding it in manually, but with no success. Please help :)

**Comment by BlackScorp** [comment]
Hey i'am so sorry, no this issues was not resolved.

actually i wanted to get rid of Grid.php and use instead "Kind". A Graph/Node for example, something more general so i can reuse it for Hexagonal Maps or even real maps. Please use v1.0.0  as for the time beeing. 

But i forgot about this issue and the time went by.. sorry i will fix this as soon as possible

**Comment by jaseyd** [comment]
Hi.
No worries. I've installed version 1.0.0 and it is working well.
Thanks for coming back to me so soon and for all your hard work on this!

**Comment by BlackScorp** [comment]
i created a new version and fixed it
